# Generated by Django 3.2.7 on 2022-11-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_idea_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
