# Generated by Django 3.2.7 on 2021-10-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210214_0451'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_recipient'),
        ),
    ]
